Repository boostcampaitech3/final-project-level3-cv-09, pull requests merged in 2022-08, with the labels that each got.

#79 기존 blood_detection blur -> bubble로 기능 추가했습니다. #76
  blood_detection/yolov5/yolov5_custom/detect.py
  blood_detection/yolov5/yolov5_custom/yolo_utils/plots.py
  pipeline/assets/alter_images/bubble.png
Labels: 💪 enhancement

#82 [feat] 데이터 추가를 위한 비디오를 이미지로 변환하는 코드 #81
  examples/ffmpeg/mp4tojpg.ipynb
  examples/ffmpeg/readme.md
Labels: 💾 data

#84 [feat] 데이터 추가를 위한 비디오를 이미지로 변환하는 코드 #81
  examples/ffmpeg/mp4tojpg_general.ipynb
Labels: 💾 data

#85 [refactoring] Add Violence filtering #80
  streamlit-fastapi-serving/fastapi/data/alter_images/bubble.png
  streamlit-fastapi-serving/fastapi/data/alter_images/mococo_0.gif
  streamlit-fastapi-serving/fastapi/data/alter_images/mococo_1.gif
  streamlit-fastapi-serving/fastapi/data/alter_images/mococo_2.gif
  streamlit-fastapi-serving/fastapi/data/alter_images/mococo_3.gif
  streamlit-fastapi-serving/fastapi/data/alter_images/pngegg.png:Zone.Identifier
  streamlit-fastapi-serving/fastapi/data/blood.yaml
  streamlit-fastapi-serving/fastapi/export.py
  streamlit-fastapi-serving/fastapi/inference/blood_detection.py
  streamlit-fastapi-serving/fastapi/inference/kinetics_violence_localization.py
  streamlit-fastapi-serving/fastapi/inference/viodet_video.py
  streamlit-fastapi-serving/fastapi/models/common.py
  streamlit-fastapi-serving/fastapi/models/experimental.py
  streamlit-fastapi-serving/fastapi/models/yolo.py
  streamlit-fastapi-serving/fastapi/server.py
  streamlit-fastapi-serving/fastapi/yolo_utils/__init__.py
  streamlit-fastapi-serving/fastapi/yolo_utils/activations.py
  streamlit-fastapi-serving/fastapi/yolo_utils/augmentations.py
  streamlit-fastapi-serving/fastapi/yolo_utils/autoanchor.py
  streamlit-fastapi-serving/fastapi/yolo_utils/autobatch.py
  streamlit-fastapi-serving/fastapi/yolo_utils/aws/__init__.py
  streamlit-fastapi-serving/fastapi/yolo_utils/aws/mime.sh
  streamlit-fastapi-serving/fastapi/yolo_utils/aws/resume.py
  streamlit-fastapi-serving/fastapi/yolo_utils/aws/userdata.sh
  streamlit-fastapi-serving/fastapi/yolo_utils/benchmarks.py
  streamlit-fastapi-serving/fastapi/yolo_utils/callbacks.py
  streamlit-fastapi-serving/fastapi/yolo_utils/dataloaders.py
  streamlit-fastapi-serving/fastapi/yolo_utils/docker/.dockerignore
  streamlit-fastapi-serving/fastapi/yolo_utils/docker/Dockerfile
  streamlit-fastapi-serving/fastapi/yolo_utils/docker/Dockerfile-arm64
  streamlit-fastapi-serving/fastapi/yolo_utils/docker/Dockerfile-cpu
  streamlit-fastapi-serving/fastapi/yolo_utils/downloads.py
  streamlit-fastapi-serving/fastapi/yolo_utils/flask_rest_api/README.md
  streamlit-fastapi-serving/fastapi/yolo_utils/flask_rest_api/example_request.py
  streamlit-fastapi-serving/fastapi/yolo_utils/flask_rest_api/restapi.py
  streamlit-fastapi-serving/fastapi/yolo_utils/general.py
  streamlit-fastapi-serving/fastapi/yolo_utils/google_app_engine/Dockerfile
  streamlit-fastapi-serving/fastapi/yolo_utils/google_app_engine/additional_requirements.txt
  streamlit-fastapi-serving/fastapi/yolo_utils/google_app_engine/app.yaml
  streamlit-fastapi-serving/fastapi/yolo_utils/loggers/__init__.py
  streamlit-fastapi-serving/fastapi/yolo_utils/loggers/wandb/README.md
  streamlit-fastapi-serving/fastapi/yolo_utils/loggers/wandb/__init__.py
  streamlit-fastapi-serving/fastapi/yolo_utils/loggers/wandb/log_dataset.py
  streamlit-fastapi-serving/fastapi/yolo_utils/loggers/wandb/sweep.py
  streamlit-fastapi-serving/fastapi/yolo_utils/loggers/wandb/sweep.yaml
  streamlit-fastapi-serving/fastapi/yolo_utils/loggers/wandb/wandb_utils.py
  streamlit-fastapi-serving/fastapi/yolo_utils/loss.py
  streamlit-fastapi-serving/fastapi/yolo_utils/metrics.py
  streamlit-fastapi-serving/fastapi/yolo_utils/plots.py
  streamlit-fastapi-serving/fastapi/yolo_utils/torch_utils.py
Labels: 🏘 refactoring

#86 [refactoring] Add skip mute alter reset #80
  streamlit-fastapi-serving/fastapi/data/alter_images/pngegg.png:Zone.Identifier
  streamlit-fastapi-serving/fastapi/server.py
  streamlit-fastapi-serving/fastapi/utils/alternative.py
  streamlit-fastapi-serving/fastapi/utils/mute.py
  streamlit-fastapi-serving/fastapi/utils/skip.py
  streamlit-fastapi-serving/streamlit/assets/alter_images/bubble.png
  streamlit-fastapi-serving/streamlit/assets/alter_images/mococo_0.gif
  streamlit-fastapi-serving/streamlit/assets/alter_images/mococo_1.gif
  streamlit-fastapi-serving/streamlit/assets/alter_images/mococo_2.gif
  streamlit-fastapi-serving/streamlit/assets/alter_images/mococo_3.gif
  streamlit-fastapi-serving/streamlit/ui.py
Labels: 🏘 refactoring
